// Single source of truth for reference data.
// Imported by:
//   - db/init.js — to build CHECK constraints + validate seed data
//   - vite.config.js — when mutation endpoints validate request bodies (TODO)
//   - studio views    — to populate dropdowns
// If you need a new value, add it here and re-run `npm run db:init` so the
// CHECK constraint stays in sync.

// Teacher specializations. Superset of lesson SUBJECTS — a Biology specialist
// can still teach "Science" lessons; the major is the more granular label.
export const MAJORS = [
  "English",
  "Arabic",
  "Math",
  "Science",
  "Biology",
  "Physics",
  "Chemistry",
  "History",
  "Geography",
  "Social Studies",
  "Islamic Studies",
  "Art",
  "Music",
  "Drama",
  "Physical Education",
  "Computer Science",
  "Business Studies",
  "Economics",
  "Psychology",
];

// School year levels. Used for:
//   - teachers.grade_levels (TEXT[])  — which grades a teacher covers
//   - students.grade        (TEXT)    — which grade a student is in
export const GRADE_LEVELS = [
  "KG 1",
  "KG 2",
  "Grade 1",
  "Grade 2",
  "Grade 3",
  "Grade 4",
  "Grade 5",
  "Grade 6",
  "Grade 7",
  "Grade 8",
  "Grade 9",
  "Grade 10",
  "Grade 11",
  "Grade 12",
];

// Nationalities. Country names (not demonyms) so "UAE" not "Emirati".
// Two groups:
//   1. Pinned head — Gulf + wider Arab world, ordered for UAE-school relevance.
//      Kept first so the most-used options are always at the top of the dropdown.
//   2. Rest of the world — alphabetical, comprehensive ISO list.
// Israel is intentionally excluded.
// "Other" is the last-resort bucket.
const PINNED_NATIONALITIES = [
  "UAE",
  "Saudi Arabia",
  "Kuwait",
  "Bahrain",
  "Qatar",
  "Oman",
  "Yemen",
  "Egypt",
  "Lebanon",
  "Jordan",
  "Syria",
  "Iraq",
  "Palestine",
  "Sudan",
  "Somalia",
  "Morocco",
  "Algeria",
  "Tunisia",
  "Libya",
  "Mauritania",
  "Djibouti",
  "Comoros",
];

const REST_NATIONALITIES = [
  "Afghanistan",
  "Albania",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo (Brazzaville)",
  "Congo (Kinshasa)",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Ireland",
  "Italy",
  "Jamaica",
  "Japan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lesotho",
  "Liberia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "São Tomé and Príncipe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Türkiye",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Zambia",
  "Zimbabwe",
];

export const NATIONALITIES = [
  ...PINNED_NATIONALITIES,
  ...REST_NATIONALITIES,
  "Other",
];
