"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { ClipboardList } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";
import { EmptyState } from "@/components/ui/empty-state";
import { useSession } from "@/features/auth/session-context";
import { useStudio } from "@/features/studio-legacy/studio-context";
import { StudioComposerBar } from "@/features/studio-legacy/StudioComposerBar";
import {
  listGoalItemsByKind,
  createGoalItemFromPrompt,
  hasReferenceMaterial,
  type GoalItemRow,
} from "@/lib/data/classes";

export default function ClassHomeworkPage() {
  const { classId } = useParams<{ classId: string }>();
  const { user } = useSession();
  const { open } = useStudio();
  const [items, setItems] = useState<GoalItemRow[] | null>(null);
  const [hasReference, setHasReference] = useState<boolean | null>(null);

  const refresh = useCallback(() => {
    listGoalItemsByKind(classId, "homework").then(setItems);
    hasReferenceMaterial(classId).then(setHasReference);
  }, [classId]);

  useEffect(() => {
    refresh();
  }, [refresh]);

  async function handleCreate(prompt: string) {
    if (!user || !hasReference) return;
    await createGoalItemFromPrompt(user.id, classId, "homework", prompt);
    refresh();
  }

  return (
    <div className="flex h-full min-h-0 flex-col">
      <div className="min-h-0 flex-1 space-y-4 overflow-y-auto p-6 md:p-8">
        <p className="text-sm text-muted-foreground">
          Assignments generated by the Goal Planner, or drafted below one at a time.
        </p>
        {items === null ? (
          <p className="text-sm text-muted-foreground">Loading…</p>
        ) : items.length === 0 ? (
          <EmptyState
            icon={ClipboardList}
            title="No homework yet"
            description="Prompt the studio below for one assignment, or use the Goal Planner for a whole term."
          />
        ) : (
          <div className="space-y-3">
            {items.map((h) => (
              <Card key={h.id}>
                <CardContent className="flex items-center justify-between p-4">
                  <div>
                    <p className="text-sm font-medium">{h.title}</p>
                    {h.detail ? (
                      <p className="text-xs text-muted-foreground">{h.detail}</p>
                    ) : null}
                  </div>
                  <div className="flex items-center gap-3">
                    <StatusPill status={h.scheduled_for ? "scheduled" : "draft"} />
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => open({ title: h.title, kind: "Homework" })}
                    >
                      Open
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>
      <div className="shrink-0 border-t border-border bg-background p-4 md:px-8">
        <StudioComposerBar
          classId={classId}
          ownerId={user?.id ?? null}
          canSend={hasReference !== false}
          placeholder="e.g. A worksheet labeling the stages of cellular respiration…"
          buttonLabel="Create"
          onSubmit={handleCreate}
          onAttached={refresh}
        />
      </div>
    </div>
  );
}
