"use client";

import { Sparkles, Plus } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";
import { useStudio } from "@/features/studio-legacy/studio-context";

const HOMEWORK = [
  { id: "h1", title: "Worksheet: label the Silk Road", detail: "Due 15 Oct", status: "scheduled" as const },
  { id: "h2", title: "Reading response — Chapter 4", detail: "Due 19 Oct", status: "draft" as const },
];

export default function ClassHomeworkPage() {
  const { open } = useStudio();
  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground">
          Assignments generated by the Goal Planner, or added manually.
        </p>
        <Button variant="outline" size="sm">
          <Plus /> New homework
        </Button>
      </div>
      <div className="space-y-3">
        {HOMEWORK.map((h) => (
          <Card key={h.id}>
            <CardContent className="flex items-center justify-between p-4">
              <div>
                <p className="flex items-center gap-1.5 text-sm font-medium">
                  <Sparkles className="size-3.5 text-primary" />
                  {h.title}
                </p>
                <p className="text-xs text-muted-foreground">{h.detail}</p>
              </div>
              <div className="flex items-center gap-3">
                <StatusPill status={h.status} />
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => open({ title: h.title, kind: "Homework" })}
                >
                  Open
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
