"use client";

import { Sparkles, Plus } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";
import { useStudio } from "@/features/studio-legacy/studio-context";

const ACTIVITIES = [
  { id: "a1", title: "Map-reading group activity", detail: "In-class, 20 min", status: "scheduled" as const },
  { id: "a2", title: "Debate: overland vs. maritime trade", detail: "In-class, 30 min", status: "draft" as const },
];

export default function ClassActivitiesPage() {
  const { open } = useStudio();
  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground">
          In-class activities generated by the Goal Planner, or added manually.
        </p>
        <Button variant="outline" size="sm">
          <Plus /> New activity
        </Button>
      </div>
      <div className="space-y-3">
        {ACTIVITIES.map((a) => (
          <Card key={a.id}>
            <CardContent className="flex items-center justify-between p-4">
              <div>
                <p className="flex items-center gap-1.5 text-sm font-medium">
                  <Sparkles className="size-3.5 text-primary" />
                  {a.title}
                </p>
                <p className="text-xs text-muted-foreground">{a.detail}</p>
              </div>
              <div className="flex items-center gap-3">
                <StatusPill status={a.status} />
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => open({ title: a.title, kind: "Activity" })}
                >
                  Open
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
