"use client";

import { Sparkles, Plus } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";
import { useStudio } from "@/features/studio-legacy/studio-context";

const QUIZZES = [
  { id: "q1", title: "Trade routes — quick check", questions: 8, status: "scheduled" as const },
  { id: "q2", title: "Map skills quiz", questions: 5, status: "scheduled" as const },
  { id: "q3", title: "Vocabulary check", questions: 10, status: "draft" as const },
];

export default function ClassQuizzesPage() {
  const { open } = useStudio();
  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground">
          Auto-generated by the Goal Planner, or added manually.
        </p>
        <Button variant="outline" size="sm">
          <Plus /> New quiz
        </Button>
      </div>
      <div className="space-y-3">
        {QUIZZES.map((q) => (
          <Card key={q.id}>
            <CardContent className="flex items-center justify-between p-4">
              <div>
                <p className="flex items-center gap-1.5 text-sm font-medium">
                  <Sparkles className="size-3.5 text-primary" />
                  {q.title}
                </p>
                <p className="text-xs text-muted-foreground">
                  {q.questions} questions
                </p>
              </div>
              <div className="flex items-center gap-3">
                <StatusPill status={q.status} />
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => open({ title: q.title, kind: "Quiz" })}
                >
                  Review
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
