"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";
import { EmptyState } from "@/components/ui/empty-state";
import { useSession } from "@/features/auth/session-context";
import { useStudio } from "@/features/studio-legacy/studio-context";
import { StudioComposerBar } from "@/features/studio-legacy/StudioComposerBar";
import {
  listAssessments,
  createAssessmentFromPrompt,
  type AssessmentRow,
} from "@/lib/data/classes";

export default function ClassQuizzesPage() {
  const { classId } = useParams<{ classId: string }>();
  const { user } = useSession();
  const { open } = useStudio();
  const [items, setItems] = useState<AssessmentRow[] | null>(null);

  const refresh = useCallback(() => {
    listAssessments(classId, "quiz").then(setItems);
  }, [classId]);

  useEffect(() => {
    refresh();
  }, [refresh]);

  async function handleCreate(prompt: string) {
    if (!user) return;
    await createAssessmentFromPrompt(user.id, classId, "quiz", prompt);
    refresh();
  }

  return (
    <div className="space-y-4">
      <p className="text-sm text-muted-foreground">
        Auto-generated by the Goal Planner, or drafted below one at a time.
      </p>
      {items === null ? (
        <p className="text-sm text-muted-foreground">Loading…</p>
      ) : items.length === 0 ? (
        <EmptyState
          title="No quizzes yet"
          description="Prompt the studio below for one quiz, or use the Goal Planner for a whole term."
        />
      ) : (
        <div className="space-y-3">
          {items.map((q) => (
            <Card key={q.id}>
              <CardContent className="flex items-center justify-between p-4">
                <p className="text-sm font-medium">{q.title}</p>
                <div className="flex items-center gap-3">
                  <StatusPill status={q.status} />
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => open({ title: q.title, kind: "Quiz" })}
                  >
                    Review
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
      <StudioComposerBar
        placeholder="e.g. A 10-question quick check on the Silk Road…"
        buttonLabel="Create"
        onSubmit={handleCreate}
      />
    </div>
  );
}
