export default async function ClassQuizzesPage({
  params,
}: {
  params: Promise<{ classId: string }>;
}) {
  const { classId } = await params;
  return (
    <main>
      <h1>Quizzes</h1>
      <p>Class {classId}. Auto-generated by the Goal Planner, or manual.</p>
    </main>
  );
}
