import { Sparkles, Plus } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";

const PRESENTATIONS = [
  { id: "p1", title: "Unit 3 — Foundations deck", detail: "18 slides", status: "scheduled" as const },
  { id: "p2", title: "Unit 4 — Deep Dive deck", detail: "14 slides", status: "draft" as const },
];

export default function ClassPresentationsPage() {
  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground">
          Slide decks generated by the Goal Planner, or added manually.
        </p>
        <Button variant="outline" size="sm">
          <Plus /> New presentation
        </Button>
      </div>
      <div className="space-y-3">
        {PRESENTATIONS.map((p) => (
          <Card key={p.id}>
            <CardContent className="flex items-center justify-between p-4">
              <div>
                <p className="flex items-center gap-1.5 text-sm font-medium">
                  <Sparkles className="size-3.5 text-primary" />
                  {p.title}
                </p>
                <p className="text-xs text-muted-foreground">{p.detail}</p>
              </div>
              <div className="flex items-center gap-3">
                <StatusPill status={p.status} />
                <Button variant="outline" size="sm">
                  Open
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
