import Link from "next/link";
import { Sparkles } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";

const LESSONS = [
  { id: "l1", title: "Unit 3 — Foundations", date: "Mon, 12 Oct", status: "scheduled" as const },
  { id: "l2", title: "Unit 4 — Deep Dive", date: "Thu, 15 Oct", status: "scheduled" as const },
  { id: "l3", title: "Revision & Practice", date: "Mon, 19 Oct", status: "draft" as const },
];

export default function ClassLessonsPage() {
  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground">
          Generated by the Goal Planner, or added manually.
        </p>
        <Button asChild size="sm">
          <Link href="/goal-planner">
            <Sparkles /> New from Goal Planner
          </Link>
        </Button>
      </div>
      <div className="space-y-3">
        {LESSONS.map((l) => (
          <Card key={l.id}>
            <CardContent className="flex items-center justify-between p-4">
              <div>
                <p className="text-sm font-medium">{l.title}</p>
                <p className="text-xs text-muted-foreground">{l.date}</p>
              </div>
              <div className="flex items-center gap-3">
                <StatusPill status={l.status} />
                <Button variant="outline" size="sm">
                  Open in Studio
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
