import { Sparkles, Plus } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";

const EXAMS = [
  { id: "e1", title: "Mid-term exam", date: "28 Oct", status: "scheduled" as const, generated: true },
  { id: "e2", title: "Unit 3 test", date: "14 Oct", status: "draft" as const, generated: true },
];

export default function ClassExamsPage() {
  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground">
          Auto-generated by the Goal Planner, or added manually.
        </p>
        <Button variant="outline" size="sm">
          <Plus /> New exam
        </Button>
      </div>
      <div className="space-y-3">
        {EXAMS.map((e) => (
          <Card key={e.id}>
            <CardContent className="flex items-center justify-between p-4">
              <div>
                <p className="flex items-center gap-1.5 text-sm font-medium">
                  {e.title}
                  {e.generated ? (
                    <Sparkles className="size-3.5 text-primary" />
                  ) : null}
                </p>
                <p className="text-xs text-muted-foreground">{e.date}</p>
              </div>
              <div className="flex items-center gap-3">
                <StatusPill status={e.status} />
                <Button variant="outline" size="sm">
                  Review
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
